---
- name: This is a playbook for installing db2
  hosts: all
  tasks:
    - name: Enable a RHSM repository
      rhsm_repository:
        name: rhel-server-rhscl-7-rpms 
    - name: Install a yum package for Item python27-python-pip
      yum:
        name: python27-python-pip
        state: present
    - name: Install a yum package for Unzip
      yum:
        name: unzip
        state: present
    - name: Execute scl to prepare pip
      shell: echo pip install requests==2.7 | scl enable python27 bash
    - name: Copy file with owner and permissions
      copy:
        src: db2scripts.zip
        dest: /tmp/db2scripts.zip
        owner: root
        group: root
        mode: '0744'
    - name: ansible create /tmp/db2scripts directory
      file:
        path: /tmp/db2scripts
        state: directory
        mode: 0755
        owner: root
        group: root
    - name: ansible create /tmp/db2server directory
      file:
        path: /tmp/db2server
        state: directory
        mode: 0755
        owner: root
        group: root
    - name: Download the tar file
      become: yes
      get_url:
        url: https://s3-api.us-geo.objectstorage.softlayer.net/cpssoftware/DB2S_11.5.4_MPML.tar.gz?AWSAccessKeyId=801bc7a5cb9a49e7b5308cd8d2d7971f&Expires=1630756329&Signature=CUhMhUFJNpywIqsf4Jc7ZFMxXWs%3D
        dest: /tmp/db2server
        mode: 0755
        group: root
        owner: root
    - name: Unarchive Installation
      become: yes
      unarchive:
        src: "/tmp/db2scripts.zip"
        dest: /tmp/db2scripts
        owner: root
        group: root
        mode: '0744'
        remote_src: yes
        list_files: yes
    - name: Run Py script
      command: python2.7 /tmp/db2scripts/db2_install.py "/opt/IBM/db2/V11.1" "db2inst1" "passw0rd" "50000" "db2fenc1" "sample"
      become: yes
      become_user: root